In [1]:
# =============================================================================
# STEP 0: Force reload modules (run this first after code changes!)
# =============================================================================
import importlib
import src.data_loader
import src.features
import src.models.base
import src.models.goals
import src.models.assists
import src.models.minutes
import src.models.defcon
import src.models.clean_sheet
import src.models.bonus
import src.models.cards
import src.models.saves
import src.pipeline

importlib.reload(src.data_loader)
importlib.reload(src.features)
importlib.reload(src.models.base)
importlib.reload(src.models.goals)
importlib.reload(src.models.assists)
importlib.reload(src.models.minutes)
importlib.reload(src.models.defcon)
importlib.reload(src.models.clean_sheet)
importlib.reload(src.models.bonus)
importlib.reload(src.models.cards)
importlib.reload(src.models.saves)
importlib.reload(src.pipeline)

print("All modules reloaded.")

All modules reloaded.

In [2]:
# =============================================================================
# STEP 1: Update Data (optional - only if you need fresh gameweek data)
# =============================================================================
# !python scrape_update_data.py --gameweek 27
# !python scrape_update_data.py --auto

In [3]:
# =============================================================================
# STEP 2: Run the Pipeline
# =============================================================================
from src.pipeline import FPLPipeline

pipeline = FPLPipeline('data')
pipeline.load_data()
pipeline.compute_features()

pipeline.tune(n_iter=100, use_subprocess=True)
pipeline.train()
predictions = pipeline.predict(gameweek=28, season='2025/2026')

============================================================
LOADING DATA
============================================================
Loading player stats from: player_stats.csv
  Loaded 82,863 player-match records
  Seasons: ['2018/2019', '2019/2020', '2020/2021', '2021/2022', '2022/2023', '2023/2024', '2024/2025', '2025/2026']
Loaded 2,932 fixtures
Filtered to seasons: ['2020/2021', '2021/2022', '2022/2023', '2023/2024', '2024/2025', '2025/2026']
Current season (2025/2026): 515 active players
Final dataset: 62,590 records

============================================================
COMPUTING FEATURES
============================================================
Computing rolling features...

c:\Users\dpfin\OneDrive\Desktop\projecting_fpl_v2\src\features.py:209: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_per90_roll5'] = df.groupby('player_id')[f'{col}_per90'].transform(
c:\Users\dpfin\OneDrive\Desktop\projecting_fpl_v2\src\features.py:208: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_per90'] = df[col] / mins_90
c:\Users\dpfin\OneDrive\Desktop\projecting_fpl_v2\src\features.py:209: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_per90_roll5'] = df.groupby('player_id')[f'{col}_per90'].transform(

  Computed 127 rolling/lifetime features

============================================================
TUNING HYPERPARAMETERS WITH HOLDOUT TEST SET
============================================================

Data split (temporal):
  Train: 50,062 samples
  Test:  12,515 samples (most recent 20%)
  Test set spans: ['2024/2025', '2025/2026']

------------------------------------------------------------
PHASE 1: Hyperparameter Tuning (5-fold CV on train set)
------------------------------------------------------------

Tuning GOALS (100 trials, TimeSeriesSplit CV, MAE) in subprocess...
  Phase 1 Best CV MAE: 0.1968
  Phase 2: RFECV feature selection...
  RFECV selected 10/37 features
  Params: {'n_estimators': 240, 'max_depth': 3, 'learning_rate': 0.018263546344515585, 'min_child_weight': 9, 'colsample_bytree': 0.6314227334863362, 'subsample': 0.8709341145981159, 'reg_alpha': 0.0043136800510466845, 'reg_lambda': 0.009119167136968255}

Tuning ASSISTS (100 trials, TimeSeriesSplit CV, MAE) in subprocess...
  Phase 1 Best CV MAE: 0.1474
  Phase 2: RFECV feature selection...
  RFECV selected 9/34 features
  Params: {'n_estimators': 137, 'max_depth': 7, 'learning_rate': 0.01139183336272123, 'min_child_weight': 2, 'colsample_bytree': 0.586629898411174, 'subsample': 0.7061592010009538, 'reg_alpha': 0.0655030185822096, 'reg_lambda': 7.766270654317374}

Tuning MINUTES (100 trials, TimeSeriesSplit CV, Huber Loss) in subprocess...
  Phase 1 Best CV Huber Loss: 138.6914
  Phase 2: RFECV feature selection...
  RFECV selected 19/26 features
  Params: {'n_estimators': 228, 'max_depth': 3, 'learning_rate': 0.05761201991990994, 'min_child_weight': 8, 'colsample_bytree': 0.6347725688168588, 'subsample': 0.8152260652148083, 'reg_alpha': 0.0016351665717309037, 'reg_lambda': 9.728888154044629}

Tuning DEFCON (100 trials, TimeSeriesSplit CV, RMSE) in subprocess...
  Phase 1 Best CV RMSE: 14.8323
  Phase 2: RFECV feature selection...
  RFECV selected 17/22 features
  Params: {'n_estimators': 371, 'max_depth': 3, 'learning_rate': 0.010030460404661235, 'min_child_weight': 4, 'colsample_bytree': 0.5289476672801124, 'subsample': 0.6805384658651822, 'reg_alpha': 1.544745935441682, 'reg_lambda': 6.619324619678182}

C:\Users\dpfin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-02-25 13:25:08,958] A new study created in memory with name: no-name-fff5fa0f-c4e7-4b1f-9fcd-ce3d404dcce7

Tuning GOALS_AGAINST (100 trials, TimeSeriesSplit CV, Poisson Deviance)...
  Phase 1: Hyperparameter search (20 features)
  Team-matches: 3213, Avg conceded: 1.391

Best trial: 0. Best value: 1.36627:   1%|          | 1/100 [00:00<01:00,  1.65it/s]

[I 2026-02-25 13:25:09,567] Trial 0 finished with value: 1.366272219953137 and parameters: {'n_estimators': 144, 'max_depth': 8, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6, 'colsample_bytree': 0.4936111842654619, 'subsample': 0.662397808134481, 'reg_alpha': 0.0017073967431528124, 'reg_lambda': 2.9154431891537547}. Best is trial 0 with value: 1.366272219953137.

Best trial: 1. Best value: 1.21957:   2%|▏         | 2/100 [00:01<01:03,  1.53it/s]

[I 2026-02-25 13:25:10,251] Trial 1 finished with value: 1.2195742334979367 and parameters: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.010725209743171996, 'min_child_weight': 10, 'colsample_bytree': 0.899465584480253, 'subsample': 0.6849356442713105, 'reg_alpha': 0.005337032762603957, 'reg_lambda': 0.00541524411940254}. Best is trial 1 with value: 1.2195742334979367.

Best trial: 1. Best value: 1.21957:   3%|▎         | 3/100 [00:01<00:50,  1.94it/s]

[I 2026-02-25 13:25:10,605] Trial 2 finished with value: 1.2332190381542198 and parameters: {'n_estimators': 126, 'max_depth': 6, 'learning_rate': 0.04345454109729477, 'min_child_weight': 3, 'colsample_bytree': 0.7671117368334277, 'subsample': 0.6557975442608167, 'reg_alpha': 0.01474275315991467, 'reg_lambda': 0.029204338471814112}. Best is trial 1 with value: 1.2195742334979367.

Best trial: 3. Best value: 1.21527:   4%|▍         | 4/100 [00:02<00:51,  1.86it/s]

[I 2026-02-25 13:25:11,173] Trial 3 finished with value: 1.2152665507691651 and parameters: {'n_estimators': 164, 'max_depth': 7, 'learning_rate': 0.019721610970574007, 'min_child_weight': 6, 'colsample_bytree': 0.7554487413172255, 'subsample': 0.6185801650879991, 'reg_alpha': 0.26926469100861794, 'reg_lambda': 0.004809461967501573}. Best is trial 3 with value: 1.2152665507691651.

Best trial: 3. Best value: 1.21527:   5%|▌         | 5/100 [00:02<00:41,  2.30it/s]

[I 2026-02-25 13:25:11,427] Trial 4 finished with value: 1.3907549314850938 and parameters: {'n_estimators': 66, 'max_depth': 8, 'learning_rate': 0.26690431824362526, 'min_child_weight': 9, 'colsample_bytree': 0.5827682615040224, 'subsample': 0.6390688456025535, 'reg_alpha': 0.5456725485601477, 'reg_lambda': 0.057624872164786026}. Best is trial 3 with value: 1.2152665507691651.

Best trial: 3. Best value: 1.21527:   6%|▌         | 6/100 [00:02<00:32,  2.87it/s]

[I 2026-02-25 13:25:11,607] Trial 5 finished with value: 1.2591210387123486 and parameters: {'n_estimators': 80, 'max_depth': 5, 'learning_rate': 0.011240768803005551, 'min_child_weight': 10, 'colsample_bytree': 0.5552679889600102, 'subsample': 0.8650089137415928, 'reg_alpha': 0.017654048052495083, 'reg_lambda': 0.12030178871154672}. Best is trial 3 with value: 1.2152665507691651.

Best trial: 3. Best value: 1.21527:   8%|▊         | 8/100 [00:03<00:25,  3.58it/s]

[I 2026-02-25 13:25:11,929] Trial 6 finished with value: 1.3995272594121126 and parameters: {'n_estimators': 187, 'max_depth': 4, 'learning_rate': 0.27051668818999286, 'min_child_weight': 8, 'colsample_bytree': 0.9636993649385135, 'subsample': 0.9579309401710595, 'reg_alpha': 0.24637685958997463, 'reg_lambda': 4.869640941520899}. Best is trial 3 with value: 1.2152665507691651.
[I 2026-02-25 13:25:12,078] Trial 7 finished with value: 1.2644265702234467 and parameters: {'n_estimators': 72, 'max_depth': 4, 'learning_rate': 0.011662890273931383, 'min_child_weight': 4, 'colsample_bytree': 0.6332063738136893, 'subsample': 0.7085396127095583, 'reg_alpha': 2.0651425578959257, 'reg_lambda': 0.026730883107816707}. Best is trial 3 with value: 1.2152665507691651.

Best trial: 3. Best value: 1.21527:   9%|▉         | 9/100 [00:03<00:27,  3.29it/s]

[I 2026-02-25 13:25:12,436] Trial 8 finished with value: 1.223305169028464 and parameters: {'n_estimators': 120, 'max_depth': 6, 'learning_rate': 0.016149614799999188, 'min_child_weight': 9, 'colsample_bytree': 0.44473038620786254, 'subsample': 0.9947547746402069, 'reg_alpha': 1.2273800987852967, 'reg_lambda': 0.0062353771356731605}. Best is trial 3 with value: 1.2152665507691651.

Best trial: 3. Best value: 1.21527:  10%|█         | 10/100 [00:03<00:24,  3.71it/s]

[I 2026-02-25 13:25:12,630] Trial 9 finished with value: 1.249839262386719 and parameters: {'n_estimators': 51, 'max_depth': 7, 'learning_rate': 0.11069143219393454, 'min_child_weight': 8, 'colsample_bytree': 0.8627622080115674, 'subsample': 0.6296178606936361, 'reg_alpha': 0.02715581955282941, 'reg_lambda': 0.0029072088906598446}. Best is trial 3 with value: 1.2152665507691651.

Best trial: 10. Best value: 1.18802:  11%|█         | 11/100 [00:04<00:27,  3.28it/s]

[I 2026-02-25 13:25:13,013] Trial 10 finished with value: 1.1880179610633264 and parameters: {'n_estimators': 281, 'max_depth': 3, 'learning_rate': 0.028477486830279893, 'min_child_weight': 1, 'colsample_bytree': 0.739367854408842, 'subsample': 0.7707251581533257, 'reg_alpha': 6.903717055434719, 'reg_lambda': 0.001115347973270347}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  12%|█▏        | 12/100 [00:04<00:28,  3.08it/s]

[I 2026-02-25 13:25:13,385] Trial 11 finished with value: 1.188426545950339 and parameters: {'n_estimators': 275, 'max_depth': 3, 'learning_rate': 0.030062564615220954, 'min_child_weight': 1, 'colsample_bytree': 0.7419518599986968, 'subsample': 0.7737425087025644, 'reg_alpha': 8.84506207957569, 'reg_lambda': 0.001105682311021514}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  13%|█▎        | 13/100 [00:04<00:29,  2.92it/s]

[I 2026-02-25 13:25:13,770] Trial 12 finished with value: 1.19214512023063 and parameters: {'n_estimators': 289, 'max_depth': 3, 'learning_rate': 0.03750217828101344, 'min_child_weight': 1, 'colsample_bytree': 0.6852838512053834, 'subsample': 0.7842531262805341, 'reg_alpha': 9.737530005425517, 'reg_lambda': 0.0015206456372196403}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  14%|█▍        | 14/100 [00:05<00:30,  2.78it/s]

[I 2026-02-25 13:25:14,168] Trial 13 finished with value: 1.1883598190056817 and parameters: {'n_estimators': 297, 'max_depth': 3, 'learning_rate': 0.027279496663267264, 'min_child_weight': 1, 'colsample_bytree': 0.7906094819029568, 'subsample': 0.7765730459008863, 'reg_alpha': 9.9414505029726, 'reg_lambda': 0.001022857651841048}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  15%|█▌        | 15/100 [00:05<00:32,  2.65it/s]

[I 2026-02-25 13:25:14,585] Trial 14 finished with value: 1.2253651418995182 and parameters: {'n_estimators': 245, 'max_depth': 4, 'learning_rate': 0.060214342091472285, 'min_child_weight': 3, 'colsample_bytree': 0.837900897719021, 'subsample': 0.8484192488178854, 'reg_alpha': 2.917501960789898, 'reg_lambda': 0.5873491948343604}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  16%|█▌        | 16/100 [00:05<00:30,  2.77it/s]

[I 2026-02-25 13:25:14,908] Trial 15 finished with value: 1.229670286081023 and parameters: {'n_estimators': 235, 'max_depth': 3, 'learning_rate': 0.07005930717482292, 'min_child_weight': 2, 'colsample_bytree': 0.8113942490026711, 'subsample': 0.7539796407337818, 'reg_alpha': 0.07407432864293498, 'reg_lambda': 0.01417872560462162}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  17%|█▋        | 17/100 [00:06<00:34,  2.37it/s]

[I 2026-02-25 13:25:15,472] Trial 16 finished with value: 1.2102762723065297 and parameters: {'n_estimators': 252, 'max_depth': 5, 'learning_rate': 0.0247884405017788, 'min_child_weight': 4, 'colsample_bytree': 0.9965583851035582, 'subsample': 0.8480246667851135, 'reg_alpha': 4.215503332643248, 'reg_lambda': 0.36130491130956555}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  18%|█▊        | 18/100 [00:07<00:36,  2.23it/s]

[I 2026-02-25 13:25:15,984] Trial 17 finished with value: 1.194950659599548 and parameters: {'n_estimators': 298, 'max_depth': 4, 'learning_rate': 0.018519102780767783, 'min_child_weight': 1, 'colsample_bytree': 0.6723402165037755, 'subsample': 0.736620037974197, 'reg_alpha': 0.8620079616208756, 'reg_lambda': 0.0010867058201591187}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  19%|█▉        | 19/100 [00:07<00:33,  2.38it/s]

[I 2026-02-25 13:25:16,335] Trial 18 finished with value: 1.2097058201919164 and parameters: {'n_estimators': 218, 'max_depth': 3, 'learning_rate': 0.07985476549062798, 'min_child_weight': 5, 'colsample_bytree': 0.9203855219222474, 'subsample': 0.9000049144884733, 'reg_alpha': 4.586800098199687, 'reg_lambda': 0.01140666663917333}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  20%|██        | 20/100 [00:08<00:39,  2.03it/s]

[I 2026-02-25 13:25:16,994] Trial 19 finished with value: 1.2530660894725052 and parameters: {'n_estimators': 269, 'max_depth': 5, 'learning_rate': 0.04264132289052759, 'min_child_weight': 2, 'colsample_bytree': 0.7987898587823812, 'subsample': 0.8005828061689467, 'reg_alpha': 0.14745426556238844, 'reg_lambda': 0.0026682974883518442}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  21%|██        | 21/100 [00:08<00:37,  2.11it/s]

[I 2026-02-25 13:25:17,424] Trial 20 finished with value: 1.1882763160764611 and parameters: {'n_estimators': 215, 'max_depth': 3, 'learning_rate': 0.026277954538662357, 'min_child_weight': 2, 'colsample_bytree': 0.6266146017126286, 'subsample': 0.8150818123083002, 'reg_alpha': 1.3213313481642905, 'reg_lambda': 0.1480162108215383}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  22%|██▏       | 22/100 [00:08<00:35,  2.18it/s]

[I 2026-02-25 13:25:17,851] Trial 21 finished with value: 1.1900420034307753 and parameters: {'n_estimators': 220, 'max_depth': 3, 'learning_rate': 0.026159367791959938, 'min_child_weight': 2, 'colsample_bytree': 0.6071237368723741, 'subsample': 0.8123363293173584, 'reg_alpha': 9.793245060264313, 'reg_lambda': 0.1873279157668613}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  23%|██▎       | 23/100 [00:09<00:41,  1.87it/s]

[I 2026-02-25 13:25:18,568] Trial 22 finished with value: 1.2015371700833875 and parameters: {'n_estimators': 266, 'max_depth': 4, 'learning_rate': 0.0325533966809714, 'min_child_weight': 3, 'colsample_bytree': 0.7005569314930453, 'subsample': 0.7226940853470663, 'reg_alpha': 1.731427733094966, 'reg_lambda': 1.3946910887254487}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  24%|██▍       | 24/100 [00:10<00:41,  1.85it/s]

[I 2026-02-25 13:25:19,116] Trial 23 finished with value: 1.1887873501541484 and parameters: {'n_estimators': 296, 'max_depth': 3, 'learning_rate': 0.022527665151501505, 'min_child_weight': 1, 'colsample_bytree': 0.5131087498438186, 'subsample': 0.897805722563775, 'reg_alpha': 3.5071156311827383, 'reg_lambda': 0.06787401407573483}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  25%|██▌       | 25/100 [00:10<00:41,  1.79it/s]

[I 2026-02-25 13:25:19,714] Trial 24 finished with value: 1.1972640093442402 and parameters: {'n_estimators': 229, 'max_depth': 4, 'learning_rate': 0.015553188818073237, 'min_child_weight': 2, 'colsample_bytree': 0.7254133080659859, 'subsample': 0.8135198951833766, 'reg_alpha': 0.49720377994323356, 'reg_lambda': 0.3261924582667997}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  26%|██▌       | 26/100 [00:11<00:39,  1.85it/s]

[I 2026-02-25 13:25:20,214] Trial 25 finished with value: 1.1953718256878507 and parameters: {'n_estimators': 253, 'max_depth': 3, 'learning_rate': 0.048498418404395914, 'min_child_weight': 4, 'colsample_bytree': 0.6532300250528874, 'subsample': 0.7733718800272757, 'reg_alpha': 5.445992866520716, 'reg_lambda': 9.946126450457445}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  27%|██▋       | 27/100 [00:11<00:39,  1.86it/s]

[I 2026-02-25 13:25:20,747] Trial 26 finished with value: 1.2009809633364201 and parameters: {'n_estimators': 204, 'max_depth': 4, 'learning_rate': 0.03251026513754658, 'min_child_weight': 1, 'colsample_bytree': 0.7904707991362979, 'subsample': 0.824002911587231, 'reg_alpha': 0.7996331914837009, 'reg_lambda': 0.002363450645476534}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  28%|██▊       | 28/100 [00:12<00:38,  1.86it/s]

[I 2026-02-25 13:25:21,286] Trial 27 finished with value: 1.1942350182638504 and parameters: {'n_estimators': 275, 'max_depth': 3, 'learning_rate': 0.014903571045392533, 'min_child_weight': 2, 'colsample_bytree': 0.861634547654599, 'subsample': 0.8790423906869326, 'reg_alpha': 1.366137088219927, 'reg_lambda': 0.8514785958311338}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  29%|██▉       | 29/100 [00:12<00:38,  1.84it/s]

[I 2026-02-25 13:25:21,837] Trial 28 finished with value: 1.201119470422912 and parameters: {'n_estimators': 162, 'max_depth': 5, 'learning_rate': 0.025354358961722945, 'min_child_weight': 3, 'colsample_bytree': 0.711513955625029, 'subsample': 0.7003658490808883, 'reg_alpha': 2.4234755010717346, 'reg_lambda': 0.030342111121343454}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  30%|███       | 30/100 [00:13<00:37,  1.85it/s]

[I 2026-02-25 13:25:22,371] Trial 29 finished with value: 1.2649377590390762 and parameters: {'n_estimators': 285, 'max_depth': 3, 'learning_rate': 0.10222688324868048, 'min_child_weight': 5, 'colsample_bytree': 0.5446284622594119, 'subsample': 0.7488621218277184, 'reg_alpha': 0.0633630311598469, 'reg_lambda': 0.1650150014309832}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  31%|███       | 31/100 [00:14<00:40,  1.72it/s]

[I 2026-02-25 13:25:23,055] Trial 30 finished with value: 1.2428085638763924 and parameters: {'n_estimators': 259, 'max_depth': 4, 'learning_rate': 0.05999827714085105, 'min_child_weight': 7, 'colsample_bytree': 0.42725509558418956, 'subsample': 0.8396158297716653, 'reg_alpha': 0.0014824522730226845, 'reg_lambda': 0.011451669331499506}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  32%|███▏      | 32/100 [00:14<00:38,  1.75it/s]

[I 2026-02-25 13:25:23,595] Trial 31 finished with value: 1.1880634974537723 and parameters: {'n_estimators': 277, 'max_depth': 3, 'learning_rate': 0.03174154273522508, 'min_child_weight': 1, 'colsample_bytree': 0.7416278257736928, 'subsample': 0.7715083251026117, 'reg_alpha': 6.956980957774972, 'reg_lambda': 0.0010440279971497234}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 10. Best value: 1.18802:  33%|███▎      | 33/100 [00:15<00:39,  1.69it/s]

[I 2026-02-25 13:25:24,241] Trial 32 finished with value: 1.191091367068036 and parameters: {'n_estimators': 299, 'max_depth': 3, 'learning_rate': 0.03454462869614573, 'min_child_weight': 1, 'colsample_bytree': 0.6293414967256109, 'subsample': 0.781111651821427, 'reg_alpha': 5.2843320548740245, 'reg_lambda': 0.0018237929671229881}. Best is trial 10 with value: 1.1880179610633264.

Best trial: 33. Best value: 1.18679:  34%|███▍      | 34/100 [00:15<00:38,  1.72it/s]

[I 2026-02-25 13:25:24,799] Trial 33 finished with value: 1.1867931732889814 and parameters: {'n_estimators': 280, 'max_depth': 3, 'learning_rate': 0.02075610083784307, 'min_child_weight': 2, 'colsample_bytree': 0.7615398130743676, 'subsample': 0.7513562798786046, 'reg_alpha': 6.433152679367197, 'reg_lambda': 0.004630861627148089}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 33. Best value: 1.18679:  35%|███▌      | 35/100 [00:16<00:41,  1.58it/s]

[I 2026-02-25 13:25:25,549] Trial 34 finished with value: 1.1957596344325847 and parameters: {'n_estimators': 202, 'max_depth': 4, 'learning_rate': 0.02039902162716407, 'min_child_weight': 2, 'colsample_bytree': 0.7728845402502402, 'subsample': 0.6890696743277364, 'reg_alpha': 0.004093284282609523, 'reg_lambda': 0.0057403567639227465}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 33. Best value: 1.18679:  36%|███▌      | 36/100 [00:17<00:42,  1.49it/s]

[I 2026-02-25 13:25:26,301] Trial 35 finished with value: 1.1921344884355416 and parameters: {'n_estimators': 244, 'max_depth': 3, 'learning_rate': 0.04207594917577529, 'min_child_weight': 3, 'colsample_bytree': 0.7377381441383802, 'subsample': 0.6687570200409216, 'reg_alpha': 5.1274700298060925, 'reg_lambda': 0.0035893168614265034}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 33. Best value: 1.18679:  37%|███▋      | 37/100 [00:18<00:52,  1.21it/s]

[I 2026-02-25 13:25:27,499] Trial 36 finished with value: 1.2342720453274485 and parameters: {'n_estimators': 135, 'max_depth': 8, 'learning_rate': 0.013034055217424016, 'min_child_weight': 2, 'colsample_bytree': 0.5929234760883114, 'subsample': 0.7516337309212743, 'reg_alpha': 0.4010224213836255, 'reg_lambda': 0.007782242947636185}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 33. Best value: 1.18679:  38%|███▊      | 38/100 [00:19<00:47,  1.32it/s]

[I 2026-02-25 13:25:28,101] Trial 37 finished with value: 1.1977308203354977 and parameters: {'n_estimators': 176, 'max_depth': 4, 'learning_rate': 0.01808876165651747, 'min_child_weight': 4, 'colsample_bytree': 0.6751250989258587, 'subsample': 0.7188932034391637, 'reg_alpha': 2.600916716294845, 'reg_lambda': 0.04286475747029743}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 33. Best value: 1.18679:  39%|███▉      | 39/100 [00:20<00:58,  1.05it/s]

[I 2026-02-25 13:25:29,517] Trial 38 finished with value: 1.210926539381021 and parameters: {'n_estimators': 280, 'max_depth': 6, 'learning_rate': 0.021299406283940565, 'min_child_weight': 3, 'colsample_bytree': 0.747552593043736, 'subsample': 0.6010671845109126, 'reg_alpha': 1.4940178092839735, 'reg_lambda': 0.0170186613375605}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 33. Best value: 1.18679:  40%|████      | 40/100 [00:20<00:47,  1.27it/s]

[I 2026-02-25 13:25:29,917] Trial 39 finished with value: 1.2457042221214925 and parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.20539910138006032, 'min_child_weight': 2, 'colsample_bytree': 0.8982616359219426, 'subsample': 0.7985703079239669, 'reg_alpha': 0.9972560501553758, 'reg_lambda': 0.003690498781534452}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 33. Best value: 1.18679:  41%|████      | 41/100 [00:21<00:45,  1.31it/s]

[I 2026-02-25 13:25:30,618] Trial 40 finished with value: 1.2351102735893709 and parameters: {'n_estimators': 154, 'max_depth': 7, 'learning_rate': 0.05108246653549553, 'min_child_weight': 6, 'colsample_bytree': 0.8273016314801109, 'subsample': 0.9305674065943725, 'reg_alpha': 6.341559748144514, 'reg_lambda': 0.0018981127483067258}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 33. Best value: 1.18679:  42%|████▏     | 42/100 [00:22<00:38,  1.50it/s]

[I 2026-02-25 13:25:31,062] Trial 41 finished with value: 1.187526402463975 and parameters: {'n_estimators': 263, 'max_depth': 3, 'learning_rate': 0.029083243296938247, 'min_child_weight': 1, 'colsample_bytree': 0.7817866554087275, 'subsample': 0.7620883827107848, 'reg_alpha': 6.973767838232778, 'reg_lambda': 0.001158544596489685}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 33. Best value: 1.18679:  43%|████▎     | 43/100 [00:22<00:33,  1.69it/s]

[I 2026-02-25 13:25:31,482] Trial 42 finished with value: 1.1919735905155326 and parameters: {'n_estimators': 265, 'max_depth': 3, 'learning_rate': 0.03667955037734199, 'min_child_weight': 1, 'colsample_bytree': 0.7600362217450609, 'subsample': 0.7560732524357404, 'reg_alpha': 3.3141881429886837, 'reg_lambda': 0.0015120601190411977}. Best is trial 33 with value: 1.1867931732889814.

Best trial: 43. Best value: 1.18599:  44%|████▍     | 44/100 [00:22<00:29,  1.92it/s]

[I 2026-02-25 13:25:31,836] Trial 43 finished with value: 1.1859868546830625 and parameters: {'n_estimators': 236, 'max_depth': 3, 'learning_rate': 0.029420466583996736, 'min_child_weight': 1, 'colsample_bytree': 0.7092098459216564, 'subsample': 0.7311218185363706, 'reg_alpha': 7.10134149201567, 'reg_lambda': 0.10864690122379397}. Best is trial 43 with value: 1.1859868546830625.

Best trial: 44. Best value: 1.18571:  45%|████▌     | 45/100 [00:23<00:25,  2.16it/s]

[I 2026-02-25 13:25:32,162] Trial 44 finished with value: 1.185711826075563 and parameters: {'n_estimators': 235, 'max_depth': 3, 'learning_rate': 0.029479855727837012, 'min_child_weight': 1, 'colsample_bytree': 0.720544461570199, 'subsample': 0.7340104879184657, 'reg_alpha': 6.834525680589691, 'reg_lambda': 0.004012942840431678}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  46%|████▌     | 46/100 [00:23<00:24,  2.24it/s]

[I 2026-02-25 13:25:32,571] Trial 45 finished with value: 1.2022028216794571 and parameters: {'n_estimators': 235, 'max_depth': 4, 'learning_rate': 0.012745378605910452, 'min_child_weight': 1, 'colsample_bytree': 0.7088891537617136, 'subsample': 0.6635342054825644, 'reg_alpha': 6.829341176590109, 'reg_lambda': 0.004450477301653546}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  47%|████▋     | 47/100 [00:24<00:23,  2.27it/s]

[I 2026-02-25 13:25:33,000] Trial 46 finished with value: 1.2082499636791773 and parameters: {'n_estimators': 248, 'max_depth': 4, 'learning_rate': 0.03996472634708433, 'min_child_weight': 1, 'colsample_bytree': 0.7732377625882146, 'subsample': 0.7359504551337579, 'reg_alpha': 2.0459372353300442, 'reg_lambda': 0.007795417624018993}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  48%|████▊     | 48/100 [00:24<00:20,  2.56it/s]

[I 2026-02-25 13:25:33,272] Trial 47 finished with value: 1.1898143427779337 and parameters: {'n_estimators': 189, 'max_depth': 3, 'learning_rate': 0.022752572381286442, 'min_child_weight': 1, 'colsample_bytree': 0.843765380523394, 'subsample': 0.6870748705312015, 'reg_alpha': 3.486333416951374, 'reg_lambda': 0.07705816507498807}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  49%|████▉     | 49/100 [00:24<00:19,  2.62it/s]

[I 2026-02-25 13:25:33,636] Trial 48 finished with value: 1.1920942649586475 and parameters: {'n_estimators': 260, 'max_depth': 3, 'learning_rate': 0.017116451020871937, 'min_child_weight': 2, 'colsample_bytree': 0.6639976915999191, 'subsample': 0.7131882111179221, 'reg_alpha': 8.260722540843974, 'reg_lambda': 0.002533043896563848}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  50%|█████     | 50/100 [00:25<00:19,  2.55it/s]

[I 2026-02-25 13:25:34,049] Trial 49 finished with value: 1.1994408093878415 and parameters: {'n_estimators': 234, 'max_depth': 4, 'learning_rate': 0.027596544825386395, 'min_child_weight': 10, 'colsample_bytree': 0.8932174465169492, 'subsample': 0.7361467907787947, 'reg_alpha': 0.03510972292332197, 'reg_lambda': 0.02004041279381057}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  51%|█████     | 51/100 [00:25<00:20,  2.34it/s]

[I 2026-02-25 13:25:34,559] Trial 50 finished with value: 1.2034160964272824 and parameters: {'n_estimators': 285, 'max_depth': 3, 'learning_rate': 0.04797789319085347, 'min_child_weight': 3, 'colsample_bytree': 0.8163906202297598, 'subsample': 0.7905326988926076, 'reg_alpha': 3.8331795993459306, 'reg_lambda': 0.04189858966769301}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  52%|█████▏    | 52/100 [00:26<00:22,  2.17it/s]

[I 2026-02-25 13:25:35,096] Trial 51 finished with value: 1.187424928275636 and parameters: {'n_estimators': 278, 'max_depth': 3, 'learning_rate': 0.03007533297577068, 'min_child_weight': 1, 'colsample_bytree': 0.7227011018617439, 'subsample': 0.76488872054518, 'reg_alpha': 6.6412713922239455, 'reg_lambda': 0.0014986795177850168}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  53%|█████▎    | 53/100 [00:26<00:22,  2.09it/s]

[I 2026-02-25 13:25:35,613] Trial 52 finished with value: 1.187649121593503 and parameters: {'n_estimators': 274, 'max_depth': 3, 'learning_rate': 0.020307940658625668, 'min_child_weight': 1, 'colsample_bytree': 0.6915034970071571, 'subsample': 0.762723194063216, 'reg_alpha': 6.7192368905746305, 'reg_lambda': 0.0014652063936421988}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  54%|█████▍    | 54/100 [00:27<00:23,  1.96it/s]

[I 2026-02-25 13:25:36,203] Trial 53 finished with value: 1.199078591146037 and parameters: {'n_estimators': 269, 'max_depth': 3, 'learning_rate': 0.010760508263514107, 'min_child_weight': 1, 'colsample_bytree': 0.6508511049985538, 'subsample': 0.7612344447839428, 'reg_alpha': 0.002833030936509279, 'reg_lambda': 0.001539400401025445}. Best is trial 44 with value: 1.185711826075563.

Best trial: 44. Best value: 1.18571:  55%|█████▌    | 55/100 [00:27<00:22,  1.98it/s]

[I 2026-02-25 13:25:36,694] Trial 54 finished with value: 1.1862433289137209 and parameters: {'n_estimators': 255, 'max_depth': 3, 'learning_rate': 0.022756755691285102, 'min_child_weight': 2, 'colsample_bytree': 0.6885671534612555, 'subsample': 0.7265871734636862, 'reg_alpha': 4.709146677601261, 'reg_lambda': 0.004192030697747547}. Best is trial 44 with value: 1.185711826075563.

Best trial: 55. Best value: 1.18367:  56%|█████▌    | 56/100 [00:28<00:21,  2.05it/s]

[I 2026-02-25 13:25:37,142] Trial 55 finished with value: 1.1836733195499123 and parameters: {'n_estimators': 225, 'max_depth': 3, 'learning_rate': 0.02924500028199792, 'min_child_weight': 2, 'colsample_bytree': 0.7167611101780376, 'subsample': 0.6456837944783226, 'reg_alpha': 2.567182868492154, 'reg_lambda': 0.008490345851065567}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  57%|█████▋    | 57/100 [00:28<00:22,  1.93it/s]

[I 2026-02-25 13:25:37,729] Trial 56 finished with value: 1.1909392484625148 and parameters: {'n_estimators': 227, 'max_depth': 4, 'learning_rate': 0.02308353326349524, 'min_child_weight': 2, 'colsample_bytree': 0.7198875099244209, 'subsample': 0.6404683963341835, 'reg_alpha': 2.232305256301515, 'reg_lambda': 0.008311497180780423}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  58%|█████▊    | 58/100 [00:29<00:25,  1.65it/s]

[I 2026-02-25 13:25:38,539] Trial 57 finished with value: 1.199664284412647 and parameters: {'n_estimators': 242, 'max_depth': 5, 'learning_rate': 0.014225363219723397, 'min_child_weight': 3, 'colsample_bytree': 0.6930100144631863, 'subsample': 0.6754934524851011, 'reg_alpha': 4.475732107392429, 'reg_lambda': 0.005704699003349612}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  59%|█████▉    | 59/100 [00:30<00:22,  1.80it/s]

[I 2026-02-25 13:25:38,982] Trial 58 finished with value: 1.1945293003643687 and parameters: {'n_estimators': 214, 'max_depth': 3, 'learning_rate': 0.03672170385903996, 'min_child_weight': 7, 'colsample_bytree': 0.7243068698754325, 'subsample': 0.6485267229415534, 'reg_alpha': 0.007968793927054381, 'reg_lambda': 0.004523906564297381}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  60%|██████    | 60/100 [00:30<00:21,  1.85it/s]

[I 2026-02-25 13:25:39,483] Trial 59 finished with value: 1.1870385642031824 and parameters: {'n_estimators': 254, 'max_depth': 3, 'learning_rate': 0.029583239217336736, 'min_child_weight': 2, 'colsample_bytree': 0.6470424090922494, 'subsample': 0.7020723495885691, 'reg_alpha': 9.678518823826161, 'reg_lambda': 0.0031955991283081427}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  61%|██████    | 61/100 [00:31<00:28,  1.35it/s]

[I 2026-02-25 13:25:40,686] Trial 60 finished with value: 1.2015326154404815 and parameters: {'n_estimators': 190, 'max_depth': 4, 'learning_rate': 0.01832784315801213, 'min_child_weight': 4, 'colsample_bytree': 0.5762333435528146, 'subsample': 0.6998509190155824, 'reg_alpha': 9.981411447581541, 'reg_lambda': 0.003327493539708162}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  62%|██████▏   | 62/100 [00:32<00:26,  1.41it/s]

[I 2026-02-25 13:25:41,326] Trial 61 finished with value: 1.1878193969174498 and parameters: {'n_estimators': 257, 'max_depth': 3, 'learning_rate': 0.030386125065728183, 'min_child_weight': 2, 'colsample_bytree': 0.6521631963495585, 'subsample': 0.6235789213156792, 'reg_alpha': 2.997776095422195, 'reg_lambda': 0.10924125592606032}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  63%|██████▎   | 63/100 [00:33<00:25,  1.44it/s]

[I 2026-02-25 13:25:41,980] Trial 62 finished with value: 1.187508483935416 and parameters: {'n_estimators': 242, 'max_depth': 3, 'learning_rate': 0.02429082714197888, 'min_child_weight': 2, 'colsample_bytree': 0.6139144703046182, 'subsample': 0.7295740297152238, 'reg_alpha': 4.615180399856507, 'reg_lambda': 0.010187452018910624}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  64%|██████▍   | 64/100 [00:33<00:24,  1.46it/s]

[I 2026-02-25 13:25:42,652] Trial 63 finished with value: 1.1888851326941565 and parameters: {'n_estimators': 225, 'max_depth': 3, 'learning_rate': 0.027926085100454395, 'min_child_weight': 2, 'colsample_bytree': 0.6843520845421984, 'subsample': 0.744243263787629, 'reg_alpha': 0.15910457750299922, 'reg_lambda': 0.002235124557418098}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  65%|██████▌   | 65/100 [00:34<00:25,  1.36it/s]

[I 2026-02-25 13:25:43,505] Trial 64 finished with value: 1.192440004065378 and parameters: {'n_estimators': 288, 'max_depth': 3, 'learning_rate': 0.034589109895483076, 'min_child_weight': 3, 'colsample_bytree': 0.6400729420146571, 'subsample': 0.7065751518153044, 'reg_alpha': 1.7568892100245517, 'reg_lambda': 0.0031537029222815276}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  66%|██████▌   | 66/100 [00:35<00:25,  1.32it/s]

[I 2026-02-25 13:25:44,318] Trial 65 finished with value: 1.1881299137899795 and parameters: {'n_estimators': 254, 'max_depth': 3, 'learning_rate': 0.020773680297954455, 'min_child_weight': 9, 'colsample_bytree': 0.7514270344057975, 'subsample': 0.7215001685471588, 'reg_alpha': 8.14433943888096, 'reg_lambda': 0.2430283891087762}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  67%|██████▋   | 67/100 [00:35<00:23,  1.42it/s]

[I 2026-02-25 13:25:44,886] Trial 66 finished with value: 1.1936002019030665 and parameters: {'n_estimators': 207, 'max_depth': 3, 'learning_rate': 0.04618406608726171, 'min_child_weight': 2, 'colsample_bytree': 0.7050794633240675, 'subsample': 0.6939128854947172, 'reg_alpha': 2.7514247985784666, 'reg_lambda': 0.0046798666352074565}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  68%|██████▊   | 68/100 [00:36<00:20,  1.55it/s]

[I 2026-02-25 13:25:45,404] Trial 67 finished with value: 1.1993126058388763 and parameters: {'n_estimators': 236, 'max_depth': 3, 'learning_rate': 0.05704991934138209, 'min_child_weight': 1, 'colsample_bytree': 0.6673793697414302, 'subsample': 0.6778935984424258, 'reg_alpha': 5.374445514422002, 'reg_lambda': 0.021480183676340282}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  69%|██████▉   | 69/100 [00:37<00:25,  1.20it/s]

[I 2026-02-25 13:25:46,682] Trial 68 finished with value: 1.1972414128140536 and parameters: {'n_estimators': 248, 'max_depth': 4, 'learning_rate': 0.039751496885782424, 'min_child_weight': 2, 'colsample_bytree': 0.7955622047893706, 'subsample': 0.655651126154979, 'reg_alpha': 9.980610668532497, 'reg_lambda': 0.014280879883049383}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  70%|███████   | 70/100 [00:38<00:25,  1.19it/s]

[I 2026-02-25 13:25:47,519] Trial 69 finished with value: 1.2075161425974563 and parameters: {'n_estimators': 271, 'max_depth': 3, 'learning_rate': 0.06680960728251552, 'min_child_weight': 3, 'colsample_bytree': 0.7251798648127351, 'subsample': 0.741784638037909, 'reg_alpha': 4.203520247074102, 'reg_lambda': 0.006738459706205044}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  71%|███████   | 71/100 [00:39<00:27,  1.07it/s]

[I 2026-02-25 13:25:48,681] Trial 70 finished with value: 1.1917310751048302 and parameters: {'n_estimators': 210, 'max_depth': 4, 'learning_rate': 0.025129095656574948, 'min_child_weight': 1, 'colsample_bytree': 0.7606895978470664, 'subsample': 0.7264950438147028, 'reg_alpha': 0.7230276546433952, 'reg_lambda': 0.002063543162799402}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  72%|███████▏  | 72/100 [00:40<00:22,  1.22it/s]

[I 2026-02-25 13:25:49,232] Trial 71 finished with value: 1.1871642654846875 and parameters: {'n_estimators': 243, 'max_depth': 3, 'learning_rate': 0.023005880421017023, 'min_child_weight': 2, 'colsample_bytree': 0.6131776696794918, 'subsample': 0.7287769994502349, 'reg_alpha': 4.598815874133784, 'reg_lambda': 0.01016953957326957}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  73%|███████▎  | 73/100 [00:41<00:21,  1.26it/s]

[I 2026-02-25 13:25:49,975] Trial 72 finished with value: 1.194013418627288 and parameters: {'n_estimators': 226, 'max_depth': 3, 'learning_rate': 0.016513472138945957, 'min_child_weight': 2, 'colsample_bytree': 0.561625176426764, 'subsample': 0.7091092285253512, 'reg_alpha': 5.57614547083251, 'reg_lambda': 0.010919144696061206}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  74%|███████▍  | 74/100 [00:41<00:20,  1.24it/s]

[I 2026-02-25 13:25:50,799] Trial 73 finished with value: 1.1874221152888809 and parameters: {'n_estimators': 252, 'max_depth': 3, 'learning_rate': 0.032592549439960046, 'min_child_weight': 2, 'colsample_bytree': 0.611337385655175, 'subsample': 0.7916352577181051, 'reg_alpha': 3.661875881602006, 'reg_lambda': 0.004047096196668403}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  75%|███████▌  | 75/100 [00:42<00:17,  1.39it/s]

[I 2026-02-25 13:25:51,314] Trial 74 finished with value: 1.1877406404537596 and parameters: {'n_estimators': 239, 'max_depth': 3, 'learning_rate': 0.03367063459746315, 'min_child_weight': 3, 'colsample_bytree': 0.6143849914038364, 'subsample': 0.6022006832591443, 'reg_alpha': 3.5597700444652354, 'reg_lambda': 0.005478023415343572}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  76%|███████▌  | 76/100 [00:42<00:15,  1.53it/s]

[I 2026-02-25 13:25:51,814] Trial 75 finished with value: 1.1848543223710208 and parameters: {'n_estimators': 253, 'max_depth': 3, 'learning_rate': 0.022328275682455597, 'min_child_weight': 2, 'colsample_bytree': 0.5410806349495814, 'subsample': 0.7900427198875157, 'reg_alpha': 2.163015332648449, 'reg_lambda': 0.003942432647237661}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  77%|███████▋  | 77/100 [00:43<00:14,  1.61it/s]

[I 2026-02-25 13:25:52,368] Trial 76 finished with value: 1.1907740816246268 and parameters: {'n_estimators': 220, 'max_depth': 3, 'learning_rate': 0.01876557363871249, 'min_child_weight': 2, 'colsample_bytree': 0.5285315160570976, 'subsample': 0.730519098740941, 'reg_alpha': 1.073247924104753, 'reg_lambda': 0.0028621149451434087}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  78%|███████▊  | 78/100 [00:45<00:20,  1.07it/s]

[I 2026-02-25 13:25:54,042] Trial 77 finished with value: 1.2162075615287873 and parameters: {'n_estimators': 249, 'max_depth': 7, 'learning_rate': 0.02221177727519109, 'min_child_weight': 5, 'colsample_bytree': 0.5891786056103375, 'subsample': 0.7176262412083152, 'reg_alpha': 2.040453188300864, 'reg_lambda': 0.009252092330462789}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  79%|███████▉  | 79/100 [00:46<00:20,  1.02it/s]

[I 2026-02-25 13:25:55,112] Trial 78 finished with value: 1.2116414153629314 and parameters: {'n_estimators': 196, 'max_depth': 6, 'learning_rate': 0.02452624136681212, 'min_child_weight': 3, 'colsample_bytree': 0.48735422931055244, 'subsample': 0.9910158684295108, 'reg_alpha': 1.692492636379668, 'reg_lambda': 0.006887041560501088}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  80%|████████  | 80/100 [00:46<00:16,  1.22it/s]

[I 2026-02-25 13:25:55,557] Trial 79 finished with value: 1.2589057327083095 and parameters: {'n_estimators': 231, 'max_depth': 3, 'learning_rate': 0.16574568374504028, 'min_child_weight': 4, 'colsample_bytree': 0.4700952608973894, 'subsample': 0.826087339582276, 'reg_alpha': 2.86329615259842, 'reg_lambda': 0.02435696639703838}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  81%|████████  | 81/100 [00:47<00:14,  1.28it/s]

[I 2026-02-25 13:25:56,255] Trial 80 finished with value: 1.1867499075712442 and parameters: {'n_estimators': 258, 'max_depth': 3, 'learning_rate': 0.026839768324807955, 'min_child_weight': 2, 'colsample_bytree': 0.6831665421497602, 'subsample': 0.7794643935506511, 'reg_alpha': 5.143356144384757, 'reg_lambda': 0.014652500051642694}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  82%|████████▏ | 82/100 [00:47<00:12,  1.43it/s]

[I 2026-02-25 13:25:56,761] Trial 81 finished with value: 1.188595978639405 and parameters: {'n_estimators': 256, 'max_depth': 3, 'learning_rate': 0.02681924182610857, 'min_child_weight': 2, 'colsample_bytree': 0.6310601423896496, 'subsample': 0.7819751897055354, 'reg_alpha': 7.942755830468227, 'reg_lambda': 0.016307382460417397}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  83%|████████▎ | 83/100 [00:48<00:10,  1.55it/s]

[I 2026-02-25 13:25:57,281] Trial 82 finished with value: 1.186884636877958 and parameters: {'n_estimators': 261, 'max_depth': 3, 'learning_rate': 0.019659112232269522, 'min_child_weight': 2, 'colsample_bytree': 0.6763040683163046, 'subsample': 0.7518992912556905, 'reg_alpha': 4.692011898383008, 'reg_lambda': 0.013138378325324775}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  84%|████████▍ | 84/100 [00:49<00:10,  1.51it/s]

[I 2026-02-25 13:25:57,985] Trial 83 finished with value: 1.188694176468326 and parameters: {'n_estimators': 267, 'max_depth': 3, 'learning_rate': 0.01982901830397901, 'min_child_weight': 3, 'colsample_bytree': 0.6784290739934864, 'subsample': 0.807494025449476, 'reg_alpha': 5.724899948442523, 'reg_lambda': 0.033135895495812015}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  85%|████████▌ | 85/100 [00:49<00:10,  1.40it/s]

[I 2026-02-25 13:25:58,813] Trial 84 finished with value: 1.1925791923473976 and parameters: {'n_estimators': 292, 'max_depth': 3, 'learning_rate': 0.014075606253050505, 'min_child_weight': 1, 'colsample_bytree': 0.7372755619605131, 'subsample': 0.7518622876021369, 'reg_alpha': 7.664260806825251, 'reg_lambda': 0.012291701019968255}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  86%|████████▌ | 86/100 [00:50<00:09,  1.44it/s]

[I 2026-02-25 13:25:59,468] Trial 85 finished with value: 1.1888005752990607 and parameters: {'n_estimators': 262, 'max_depth': 3, 'learning_rate': 0.017240208487241893, 'min_child_weight': 2, 'colsample_bytree': 0.6913021576388344, 'subsample': 0.7706102118411249, 'reg_alpha': 2.4858044528578245, 'reg_lambda': 0.08004388054666343}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  87%|████████▋ | 87/100 [00:51<00:09,  1.31it/s]

[I 2026-02-25 13:26:00,399] Trial 86 finished with value: 1.1939620769543797 and parameters: {'n_estimators': 279, 'max_depth': 4, 'learning_rate': 0.01546695454218943, 'min_child_weight': 3, 'colsample_bytree': 0.6620359728908616, 'subsample': 0.744486241601648, 'reg_alpha': 5.711163521566333, 'reg_lambda': 0.006555874113449409}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  88%|████████▊ | 88/100 [00:51<00:08,  1.45it/s]

[I 2026-02-25 13:26:00,905] Trial 87 finished with value: 1.1861798444546099 and parameters: {'n_estimators': 262, 'max_depth': 3, 'learning_rate': 0.02902272424423361, 'min_child_weight': 1, 'colsample_bytree': 0.7056537045025845, 'subsample': 0.6993798780105528, 'reg_alpha': 3.8335504516594505, 'reg_lambda': 0.00358044932420871}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  89%|████████▉ | 89/100 [00:52<00:07,  1.57it/s]

[I 2026-02-25 13:26:01,427] Trial 88 finished with value: 1.1885141461261555 and parameters: {'n_estimators': 262, 'max_depth': 3, 'learning_rate': 0.019293747284527287, 'min_child_weight': 1, 'colsample_bytree': 0.7087255646510962, 'subsample': 0.7943229611631358, 'reg_alpha': 1.3980846502933741, 'reg_lambda': 0.004868804276665244}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  90%|█████████ | 90/100 [00:53<00:06,  1.50it/s]

[I 2026-02-25 13:26:02,159] Trial 89 finished with value: 1.194461211707784 and parameters: {'n_estimators': 270, 'max_depth': 4, 'learning_rate': 0.02629566653094926, 'min_child_weight': 1, 'colsample_bytree': 0.41656518007845167, 'subsample': 0.7846319633014099, 'reg_alpha': 3.026563262633284, 'reg_lambda': 0.05242997109189908}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  91%|█████████ | 91/100 [00:53<00:06,  1.49it/s]

[I 2026-02-25 13:26:02,849] Trial 90 finished with value: 1.2016812588525918 and parameters: {'n_estimators': 292, 'max_depth': 3, 'learning_rate': 0.010002497221669527, 'min_child_weight': 1, 'colsample_bytree': 0.7806785577559902, 'subsample': 0.8054145739460921, 'reg_alpha': 4.144147646125155, 'reg_lambda': 0.013573950501177903}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  92%|█████████▏| 92/100 [00:54<00:05,  1.54it/s]

[I 2026-02-25 13:26:03,447] Trial 91 finished with value: 1.185927526870215 and parameters: {'n_estimators': 250, 'max_depth': 3, 'learning_rate': 0.03046221507974817, 'min_child_weight': 2, 'colsample_bytree': 0.6805528555820874, 'subsample': 0.6966979888895729, 'reg_alpha': 8.139396057249142, 'reg_lambda': 0.0038598482551874492}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  93%|█████████▎| 93/100 [00:55<00:04,  1.52it/s]

[I 2026-02-25 13:26:04,125] Trial 92 finished with value: 1.1867291270056701 and parameters: {'n_estimators': 282, 'max_depth': 3, 'learning_rate': 0.02192628959487171, 'min_child_weight': 2, 'colsample_bytree': 0.6988058121585258, 'subsample': 0.6817782750966968, 'reg_alpha': 4.927935260972234, 'reg_lambda': 0.0038885489786538436}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  94%|█████████▍| 94/100 [00:55<00:03,  1.60it/s]

[I 2026-02-25 13:26:04,676] Trial 93 finished with value: 1.1883710646577441 and parameters: {'n_estimators': 283, 'max_depth': 3, 'learning_rate': 0.021657809107262928, 'min_child_weight': 1, 'colsample_bytree': 0.7324549020849717, 'subsample': 0.6831813936701212, 'reg_alpha': 6.356883175239912, 'reg_lambda': 0.0035840574148795355}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  95%|█████████▌| 95/100 [00:57<00:05,  1.00s/it]

[I 2026-02-25 13:26:06,562] Trial 94 finished with value: 1.238711536569872 and parameters: {'n_estimators': 275, 'max_depth': 8, 'learning_rate': 0.028773211515054194, 'min_child_weight': 2, 'colsample_bytree': 0.712257124639534, 'subsample': 0.6695409990133127, 'reg_alpha': 2.1260779262509426, 'reg_lambda': 0.002491261964425222}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  96%|█████████▌| 96/100 [00:58<00:03,  1.17it/s]

[I 2026-02-25 13:26:07,059] Trial 95 finished with value: 1.1871507688742404 and parameters: {'n_estimators': 247, 'max_depth': 3, 'learning_rate': 0.02463671723181345, 'min_child_weight': 1, 'colsample_bytree': 0.6991734279224777, 'subsample': 0.6922968219598121, 'reg_alpha': 8.036891485674436, 'reg_lambda': 0.004221033228173998}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  97%|█████████▋| 97/100 [00:58<00:02,  1.34it/s]

[I 2026-02-25 13:26:07,551] Trial 96 finished with value: 1.1875104148875786 and parameters: {'n_estimators': 239, 'max_depth': 3, 'learning_rate': 0.03061530845724527, 'min_child_weight': 1, 'colsample_bytree': 0.759088992578747, 'subsample': 0.6304029377221553, 'reg_alpha': 3.5572940509708486, 'reg_lambda': 2.5701046712058595}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367:  98%|█████████▊| 98/100 [00:59<00:01,  1.44it/s]

[I 2026-02-25 13:26:08,129] Trial 97 finished with value: 1.193721681107813 and parameters: {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.026813858519985783, 'min_child_weight': 2, 'colsample_bytree': 0.7471411984639321, 'subsample': 0.655348604881586, 'reg_alpha': 0.0010006615208388158, 'reg_lambda': 0.005418721759507948}. Best is trial 55 with value: 1.1836733195499123.

Best trial: 55. Best value: 1.18367: 100%|██████████| 100/100 [00:59<00:00,  1.68it/s]

[I 2026-02-25 13:26:08,454] Trial 98 finished with value: 1.187630320204109 and parameters: {'n_estimators': 232, 'max_depth': 3, 'learning_rate': 0.03805387107142591, 'min_child_weight': 2, 'colsample_bytree': 0.6611166274769747, 'subsample': 0.7119684588516022, 'reg_alpha': 4.910996899702898, 'reg_lambda': 0.13054391305935614}. Best is trial 55 with value: 1.1836733195499123.
[I 2026-02-25 13:26:08,575] Trial 99 finished with value: 1.2454985477418474 and parameters: {'n_estimators': 57, 'max_depth': 3, 'learning_rate': 0.02270135094188755, 'min_child_weight': 1, 'colsample_bytree': 0.686775621183227, 'subsample': 0.6992252497575707, 'reg_alpha': 7.252945344049959, 'reg_lambda': 0.0019640861368218484}. Best is trial 55 with value: 1.1836733195499123.
  Best CV Poisson Deviance: 1.1837
  Phase 2: RFECV feature selection with best hyperparams...
  RFECV selected 20/20 features
  Params: {'n_estimators': 225, 'max_depth': 3, 'learning_rate': 0.02924500028199792, 'min_child_weight': 2, 'colsample_bytree': 0.7167611101780376, 'subsample': 0.6456837944783226, 'reg_alpha': 2.567182868492154, 'reg_lambda': 0.008490345851065567}

Tuning SAVES (100 trials, TimeSeriesSplit CV, MAE) in subprocess...
  Phase 1 Best CV MAE: 1.5524
  Phase 2: RFECV feature selection...
  RFECV selected 20/20 features
  Params: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.030512239847784735, 'min_child_weight': 5, 'colsample_bytree': 0.6510638063380768, 'subsample': 0.7125657038315838, 'reg_alpha': 3.988956930078285, 'reg_lambda': 1.1894275613911425}

------------------------------------------------------------
PHASE 2: Evaluation on Held-Out Test Set
------------------------------------------------------------

Model           Metric          Test Value   MAE
------------------------------------------------------
GOALS           MAE             0.1837       0.1837
ASSISTS         MAE             0.1357       0.1357
MINUTES         Huber Loss      142.6213     18.5371
DEFCON          RMSE            14.0009      5.6287
SAVES           MAE             1.4385       1.4385
CLEAN_SHEET     Poisson Dev     1.1246       0.8712

(Lower is better for all metrics)
MAE: mean absolute error | RMSE: root mean squared error | Huber: robust to outliers

============================================================
TUNING COMPLETE
Tuned params stored. Call train() to train final models on ALL data.
============================================================

============================================================
TRAINING FINAL MODELS ON ALL DATA
(using tuned hyperparameters)
============================================================
Training MinutesModel on 62,577 samples...
  90 min: 52.8%, 60+ min: 71.5%
  MAE: 17.6
Training CleanSheetModel (Goals Against) on 3,952 team-matches (20 features, tuned selection)...
  Avg goals conceded: 1.377
  Actual CS rate: 27.5%
  Calibration: raw CS prob mean=0.255, calibrated=0.263, actual=0.263
  MAE (goals against): 0.893
  Predicted CS prob (mean): 28.3%
  Predicted 2+ conceded prob (mean): 39.0%

Generating leak-free predicted team goals (TimeSeriesSplit OOF)...

c:\Users\dpfin\OneDrive\Desktop\projecting_fpl_v2\src\pipeline.py:264: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.df['opponent_norm'] = self.df['opponent'].apply(normalize_name)

  Mapped pred_team_goals to 62,590/62,590 player rows
  Mean pred_team_goals: 1.411
Training GoalsModel on 62,577 samples (11 features, tuned selection)...
  Target mean: 0.1071
  MAE: 0.1923
Training AssistsModel on 62,577 samples (10 features, tuned selection)...
  Target mean: 0.0761
  MAE: 0.1437
Training DefconModel on 62,577 samples...
  Mean defcon/90: 8.22
  MAE: 3.88
Training BonusModel (Monte Carlo, 1000 sims)...
  Estimating baseline BPS from stats (no actual BPS data)
Training BaselineBPSModel on 44721 samples...
  Features used: 30
  Avg baseline BPS: 18.7
  MAE: 0.69
  Loaded FPL availability for 1604 players
Training CardsModel on 62,577 samples (14 features)...
  Mean fouls/90: 0.851
  MAE: 0.873
Training SavesModel on 4,337 GK samples (20 features, tuned selection)...
  Mean saves/90: 3.00
  MAE: 1.471

============================================================
PREDICTING GW28 (2025/2026)
============================================================
Found 514 active players with historical data
  Filtered out 81 unavailable players (injured/suspended)
  Fetched 10 GW28 fixtures from FPL API
    Wolves vs Aston Villa
    Bournemouth vs Sunderland
    Burnley vs Brentford
    Liverpool vs West Ham
    Newcastle vs Everton
    Leeds vs Man City
    Brighton vs Nott'm Forest
    Fulham vs Spurs
    Man Utd vs Crystal Palace
    Arsenal vs Chelsea
Matched 433 player-fixtures to GW28 (433 players)

Saved predictions to: data\predictions\gw28_2025-2026.csv
Total players: 433

In [10]:
# =============================================================================
# STEP 3: View Top Players
# =============================================================================
# Top 20 by expected points with full prediction breakdown
display_cols = [
    'player_name', 'team', 'fpl_position', 'opponent', 'is_home',
    'pred_minutes', 'pred_exp_goals', 'pred_exp_assists', 
    'pred_cs_prob', 'pred_2plus_conceded', 'pred_4plus_conceded',
    'pred_defcon_prob', 'pred_exp_saves',
    'pred_yellow_prob', 'pred_red_prob',
    'pred_bonus', 'exp_total_pts'
]
available_cols = [c for c in display_cols if c in predictions.columns]
predictions.loc[predictions['fpl_position']!="GK"].nlargest(20, 'exp_total_pts')[available_cols].round(2)

,player_name,team,fpl_position,opponent,is_home,pred_minutes,pred_exp_goals,pred_exp_assists,pred_cs_prob,pred_2plus_conceded,pred_4plus_conceded,pred_defcon_prob,pred_exp_saves,pred_yellow_prob,pred_red_prob,pred_bonus,exp_total_pts
39,Mohamed Salah,Liverpool,MID,West Ham,1,88.000000,0.51,0.25,0.37,0.23,0.01,0.00,0.0,0.06,0.00,0.70,6.29
362,Igor Thiago,Brentford,FWD,Burnley,0,88.000000,0.55,0.10,0.15,0.58,0.14,0.01,0.0,0.20,0.01,1.08,5.36
159,Gabriel,Arsenal,DEF,Chelsea,1,88.120003,0.08,0.04,0.51,0.14,0.00,0.20,0.0,0.11,0.00,0.31,5.09
52,Bruno Fernandes,Manchester United,MID,Crystal Palace,1,88.160004,0.27,0.22,0.36,0.31,0.03,0.16,0.0,0.12,0.00,0.52,5.08
123,Erling Haaland,Manchester City,FWD,Leeds,0,84.230003,0.44,0.12,0.24,0.46,0.07,0.00,0.0,0.11,0.00,0.83,4.83
278,Kevin Schade,Brentford,MID,Burnley,0,80.000000,0.38,0.13,0.15,0.58,0.14,0.01,0.0,0.17,0.00,0.56,4.83
288,Riccardo Calafiori,Arsenal,DEF,Chelsea,1,78.709999,0.09,0.05,0.51,0.14,0.00,0.07,0.0,0.14,0.00,0.19,4.79
283,Cole Palmer,Chelsea,MID,Arsenal,0,80.000000,0.33,0.12,0.37,0.25,0.02,0.01,0.0,0.08,0.00,0.38,4.69
329,Hugo Ekitike,Liverpool,FWD,West Ham,1,79.300003,0.40,0.15,0.37,0.23,0.01,0.00,0.0,0.16,0.00,0.73,4.59
227,Maxence Lacroix,Crystal Palace,DEF,Man Utd,0,88.980003,0.05,0.05,0.37,0.24,0.02,0.43,0.0,0.14,0.00,0.20,4.58
20,Virgil van Dijk,Liverpool,DEF,West Ham,1,89.129997,0.08,0.05,0.37,0.23,0.01,0.28,0.0,0.05,0.00,0.23,4.56
201,Calvin Bassey,Fulham,DEF,Spurs,1,87.529999,0.05,0.04,0.37,0.25,0.02,0.24,0.0,0.11,0.00,0.54,4.56
214,Bryan Mbeumo,Manchester United,MID,Crystal Palace,1,88.000000,0.29,0.15,0.36,0.31,0.03,0.01,0.0,0.10,0.00,0.36,4.56
345,Dango Ouattara,Brentford,MID,Burnley,0,82.260002,0.27,0.16,0.15,0.58,0.14,0.09,0.0,0.11,0.00,0.48,4.54
179,Dominik Szoboszlai,Liverpool,MID,West Ham,1,88.330002,0.21,0.21,0.37,0.23,0.01,0.14,0.0,0.15,0.00,0.38,4.53
205,Morgan Rogers,Aston Villa,MID,Wolves,0,88.510002,0.29,0.16,0.27,0.38,0.04,0.03,0.0,0.17,0.00,0.46,4.52
308,Piero Hincapié,Arsenal,DEF,Chelsea,1,81.379997,0.02,0.05,0.51,0.14,0.00,0.16,0.0,0.10,0.00,0.07,4.49
228,Chris Richards,Crystal Palace,DEF,Man Utd,0,88.779999,0.04,0.04,0.37,0.24,0.02,0.38,0.0,0.08,0.00,0.21,4.49
314,Yasin Ayari,Brighton and Hove Albion,MID,Nott'm Forest,1,88.000000,0.19,0.14,0.24,0.44,0.07,0.38,0.0,0.16,0.00,0.31,4.49
204,Anton Stach,Leeds United,MID,Man City,1,88.000000,0.16,0.19,0.27,0.39,0.05,0.38,0.0,0.21,0.01,0.30,4.43

In [5]:
# =============================================================================
# Top 10 by Position
# =============================================================================
import pandas as pd

# --- FWD & MID: ranked by expected goals + assists ---
for pos in ['FWD', 'MID']:
    df_pos = predictions[predictions['fpl_position'] == pos].copy()
    df_pos['g+a'] = df_pos['pred_exp_goals'] + df_pos['pred_exp_assists']
    cols = ['player_name', 'team', 'opponent', 'is_home',
            'pred_minutes', 'pred_exp_goals', 'pred_exp_assists', 'g+a',
            'pred_yellow_prob', 'exp_total_pts']
    available = [c for c in cols if c in df_pos.columns]
    print(f"\n{'='*70}")
    print(f"  TOP 10 {pos} (ranked by expected G+A)")
    print(f"{'='*70}")
    display(df_pos.nlargest(10, 'g+a')[available].round(2))

# --- DEF: ranked by expected total pts, showing CS/DC/2+ conceded/4+ conceded + G+A ---
df_def = predictions[predictions['fpl_position'] == 'DEF'].copy()
df_def['g+a'] = df_def['pred_exp_goals'] + df_def['pred_exp_assists']
cols_def = ['player_name', 'team', 'opponent', 'is_home',
            'pred_minutes', 'pred_exp_goals', 'pred_exp_assists', 'g+a',
            'pred_cs_prob', 'pred_2plus_conceded', 'pred_4plus_conceded',
            'pred_defcon_prob', 'pred_yellow_prob', 'exp_total_pts']
available_def = [c for c in cols_def if c in df_def.columns]
print(f"\n{'='*70}")
print(f"  TOP 10 DEF (ranked by exp total pts)")
print(f"{'='*70}")
display(df_def.nlargest(10, 'exp_total_pts')[available_def].round(2))

# --- GK: show saves predictions ---
df_gk = predictions[predictions['fpl_position'] == 'GK'].copy()
cols_gk = ['player_name', 'team', 'opponent', 'is_home',
           'pred_minutes', 'pred_exp_saves',
           'pred_cs_prob', 'pred_2plus_conceded', 'pred_4plus_conceded',
           'pred_goals_against', 'pred_yellow_prob',
           'exp_saves_pts', 'exp_total_pts']
available_gk = [c for c in cols_gk if c in df_gk.columns]
print(f"\n{'='*70}")
print(f"  TOP 10 GK (ranked by exp total pts)")
print(f"{'='*70}")
display(df_gk.nlargest(10, 'exp_total_pts')[available_gk].round(2))

# --- FULL POINTS BREAKDOWN: Top 20 players ---
print(f"\n{'='*70}")
print(f"  FULL POINTS BREAKDOWN - TOP 20")
print(f"{'='*70}")
pts_cols = ['player_name', 'team', 'fpl_position', 'opponent',
            'exp_appearance_pts', 'exp_goals_pts', 'exp_assists_pts',
            'exp_cs_pts', 'exp_conceded_penalty', 'exp_saves_pts',
            'exp_defcon_pts', 'exp_bonus_pts', 'exp_yellow_pts', 'exp_red_pts',
            'exp_total_pts']
available_pts = [c for c in pts_cols if c in predictions.columns]
display(predictions.nlargest(20, 'exp_total_pts')[available_pts].round(2))

======================================================================
  TOP 10 FWD (ranked by expected G+A)
======================================================================

,player_name,team,opponent,is_home,pred_minutes,pred_exp_goals,pred_exp_assists,g+a,pred_yellow_prob,exp_total_pts
362,Igor Thiago,Brentford,Burnley,0,88.000000,0.55,0.10,0.65,0.20,5.36
123,Erling Haaland,Manchester City,Leeds,0,84.230003,0.44,0.12,0.56,0.11,4.83
329,Hugo Ekitike,Liverpool,West Ham,1,79.300003,0.40,0.15,0.55,0.16,4.59
71,Ollie Watkins,Aston Villa,Wolves,0,82.930000,0.36,0.09,0.45,0.19,4.28
38,Raul Jiménez,Fulham,Spurs,1,78.139999,0.35,0.08,0.43,0.18,4.26
254,Joao Pedro,Chelsea,Arsenal,0,81.989998,0.30,0.10,0.39,0.14,3.92
85,Dominic Calvert-Lewin,Leeds United,Man City,1,84.849998,0.31,0.07,0.38,0.15,3.83
65,Jarrod Bowen,West Ham United,Liverpool,0,88.169998,0.26,0.12,0.38,0.10,3.86
285,Evanilson,Bournemouth,Sunderland,1,78.559998,0.29,0.07,0.36,0.13,3.88
101,Viktor Gyökeres,Arsenal,Chelsea,1,79.050003,0.28,0.06,0.34,0.10,3.69

======================================================================
  TOP 10 MID (ranked by expected G+A)
======================================================================

,player_name,team,opponent,is_home,pred_minutes,pred_exp_goals,pred_exp_assists,g+a,pred_yellow_prob,exp_total_pts
39,Mohamed Salah,Liverpool,West Ham,1,88.000000,0.51,0.25,0.75,0.06,6.29
278,Kevin Schade,Brentford,Burnley,0,80.000000,0.38,0.13,0.51,0.17,4.83
52,Bruno Fernandes,Manchester United,Crystal Palace,1,88.160004,0.27,0.22,0.49,0.12,5.08
283,Cole Palmer,Chelsea,Arsenal,0,80.000000,0.33,0.12,0.45,0.08,4.69
205,Morgan Rogers,Aston Villa,Wolves,0,88.510002,0.29,0.16,0.45,0.17,4.52
214,Bryan Mbeumo,Manchester United,Crystal Palace,1,88.000000,0.29,0.15,0.44,0.10,4.56
345,Dango Ouattara,Brentford,Burnley,0,82.260002,0.27,0.16,0.43,0.11,4.54
163,Cody Gakpo,Liverpool,West Ham,1,77.720001,0.28,0.15,0.42,0.14,4.38
179,Dominik Szoboszlai,Liverpool,West Ham,1,88.330002,0.21,0.21,0.42,0.15,4.53
240,Bukayo Saka,Arsenal,Chelsea,1,75.250000,0.23,0.17,0.40,0.13,4.41

======================================================================
  TOP 10 DEF (ranked by exp total pts)
======================================================================

,player_name,team,opponent,is_home,pred_minutes,pred_exp_goals,pred_exp_assists,g+a,pred_cs_prob,pred_2plus_conceded,pred_4plus_conceded,pred_defcon_prob,pred_yellow_prob,exp_total_pts
159,Gabriel,Arsenal,Chelsea,1,88.120003,0.08,0.04,0.12,0.51,0.14,0.00,0.20,0.11,5.09
288,Riccardo Calafiori,Arsenal,Chelsea,1,78.709999,0.09,0.05,0.14,0.51,0.14,0.00,0.07,0.14,4.79
227,Maxence Lacroix,Crystal Palace,Man Utd,0,88.980003,0.05,0.05,0.10,0.37,0.24,0.02,0.43,0.14,4.58
20,Virgil van Dijk,Liverpool,West Ham,1,89.129997,0.08,0.05,0.12,0.37,0.23,0.01,0.28,0.05,4.56
201,Calvin Bassey,Fulham,Spurs,1,87.529999,0.05,0.04,0.09,0.37,0.25,0.02,0.24,0.11,4.56
308,Piero Hincapié,Arsenal,Chelsea,1,81.379997,0.02,0.05,0.07,0.51,0.14,0.00,0.16,0.10,4.49
228,Chris Richards,Crystal Palace,Man Utd,0,88.779999,0.04,0.04,0.08,0.37,0.24,0.02,0.38,0.08,4.49
224,Jurrien Timber,Arsenal,Chelsea,1,88.459999,0.06,0.06,0.12,0.51,0.14,0.00,0.03,0.15,4.43
170,Jorge Cuenca,Fulham,Spurs,1,85.459999,0.03,0.05,0.08,0.37,0.25,0.02,0.40,0.11,4.39
61,Joachim Andersen,Fulham,Spurs,1,88.980003,0.04,0.04,0.08,0.37,0.25,0.02,0.34,0.10,4.37

======================================================================
  TOP 10 GK (ranked by exp total pts)
======================================================================

,player_name,team,opponent,is_home,pred_minutes,pred_exp_saves,pred_cs_prob,pred_2plus_conceded,pred_4plus_conceded,pred_goals_against,pred_yellow_prob,exp_saves_pts,exp_total_pts
76,David Raya,Arsenal,Chelsea,1,89.739998,2.68,0.51,0.14,0.00,0.65,0.00,0.89,5.17
334,Filip Jörgensen,Chelsea,Arsenal,0,87.739998,3.61,0.37,0.25,0.02,0.96,0.00,1.20,4.66
152,Robert Sánchez,Chelsea,Arsenal,0,89.690002,3.52,0.37,0.25,0.02,0.96,0.00,1.17,4.64
118,Dean Henderson,Crystal Palace,Man Utd,0,89.760002,3.15,0.37,0.24,0.02,0.93,0.01,1.05,4.58
225,Giorgi Mamardashvili,Liverpool,West Ham,1,89.629997,2.72,0.37,0.23,0.01,0.90,0.00,0.91,4.55
45,Alisson Becker,Liverpool,West Ham,1,89.739998,2.31,0.37,0.23,0.01,0.90,0.00,0.77,4.39
23,Bernd Leno,Fulham,Spurs,1,89.760002,2.44,0.37,0.25,0.02,0.96,0.02,0.81,4.36
321,Senne Lammens,Manchester United,Crystal Palace,1,89.739998,2.23,0.36,0.31,0.03,1.11,0.00,0.74,4.13
196,Altay Bayindir,Manchester United,Crystal Palace,1,89.629997,2.25,0.36,0.31,0.03,1.11,0.00,0.75,4.13
302,Robin Roefs,Sunderland,Bournemouth,0,89.760002,3.33,0.27,0.39,0.05,1.35,0.00,1.11,4.07

======================================================================
  FULL POINTS BREAKDOWN - TOP 20
======================================================================

,player_name,team,fpl_position,opponent,exp_appearance_pts,exp_goals_pts,exp_assists_pts,exp_cs_pts,exp_conceded_penalty,exp_saves_pts,exp_defcon_pts,exp_bonus_pts,exp_yellow_pts,exp_red_pts,exp_total_pts
39,Mohamed Salah,Liverpool,MID,West Ham,2.0,2.53,0.75,0.37,0.00,0.00,0.00,0.70,-0.06,-0.00,6.29
362,Igor Thiago,Brentford,FWD,Burnley,2.0,2.20,0.30,0.00,0.00,0.00,0.00,1.08,-0.20,-0.02,5.36
76,David Raya,Arsenal,GK,Chelsea,2.0,0.16,0.08,2.06,-0.14,0.89,0.00,0.13,-0.00,-0.00,5.17
159,Gabriel,Arsenal,DEF,Chelsea,2.0,0.46,0.12,2.06,-0.14,0.00,0.40,0.31,-0.11,-0.01,5.09
52,Bruno Fernandes,Manchester United,MID,Crystal Palace,2.0,1.35,0.65,0.36,0.00,0.00,0.32,0.52,-0.12,-0.01,5.08
123,Erling Haaland,Manchester City,FWD,Leeds,2.0,1.75,0.36,0.00,0.00,0.00,0.00,0.83,-0.11,-0.01,4.83
278,Kevin Schade,Brentford,MID,Burnley,2.0,1.88,0.40,0.15,0.00,0.00,0.03,0.56,-0.17,-0.01,4.83
288,Riccardo Calafiori,Arsenal,DEF,Chelsea,2.0,0.56,0.15,2.06,-0.14,0.00,0.13,0.19,-0.14,-0.01,4.79
283,Cole Palmer,Chelsea,MID,Arsenal,2.0,1.66,0.35,0.37,0.00,0.00,0.03,0.38,-0.08,-0.01,4.69
334,Filip Jörgensen,Chelsea,GK,Arsenal,2.0,0.13,0.09,1.49,-0.26,1.20,0.00,0.02,-0.00,-0.00,4.66
152,Robert Sánchez,Chelsea,GK,Arsenal,2.0,0.14,0.07,1.49,-0.26,1.17,0.00,0.04,-0.00,-0.00,4.64
329,Hugo Ekitike,Liverpool,FWD,West Ham,2.0,1.60,0.44,0.00,0.00,0.00,0.00,0.73,-0.16,-0.01,4.59
227,Maxence Lacroix,Crystal Palace,DEF,Man Utd,2.0,0.30,0.14,1.49,-0.26,0.00,0.87,0.20,-0.14,-0.01,4.58
118,Dean Henderson,Crystal Palace,GK,Man Utd,2.0,0.15,0.08,1.49,-0.26,1.05,0.00,0.06,-0.01,-0.00,4.58
20,Virgil van Dijk,Liverpool,DEF,West Ham,2.0,0.45,0.14,1.49,-0.24,0.00,0.55,0.23,-0.05,-0.00,4.56
201,Calvin Bassey,Fulham,DEF,Spurs,2.0,0.30,0.13,1.49,-0.27,0.00,0.48,0.54,-0.11,-0.01,4.56
214,Bryan Mbeumo,Manchester United,MID,Crystal Palace,2.0,1.47,0.45,0.36,0.00,0.00,0.03,0.36,-0.10,-0.01,4.56
225,Giorgi Mamardashvili,Liverpool,GK,West Ham,2.0,0.18,0.11,1.49,-0.24,0.91,0.00,0.10,-0.00,-0.00,4.55
345,Dango Ouattara,Brentford,MID,Burnley,2.0,1.36,0.48,0.15,0.00,0.00,0.18,0.48,-0.11,-0.01,4.54
179,Dominik Szoboszlai,Liverpool,MID,West Ham,2.0,1.03,0.64,0.37,0.00,0.00,0.27,0.38,-0.15,-0.01,4.53

In [6]:
predictions[predictions['player_name'].str.contains('Chal', case=False, na=False)][available_cols].round(2)

,player_name,team,fpl_position,opponent,is_home,pred_minutes,pred_exp_goals,pred_exp_assists,pred_cs_prob,pred_2plus_conceded,pred_4plus_conceded,pred_defcon_prob,pred_exp_saves,pred_yellow_prob,pred_red_prob,pred_bonus,exp_total_pts
158,Trevoh Chalobah,Chelsea,DEF,Arsenal,0,88.32,0.04,0.03,0.37,0.25,0.02,0.33,0.0,0.12,0.0,0.23,4.3

In [7]:
# =============================================================================
# Arsenal xG Analysis: Actual Last 5 Games vs Computed Rolling Features
# =============================================================================

# Get Arsenal's last 5 games from raw match data
arsenal_matches = pipeline.df[
    (pipeline.df['team'].str.contains('Arsenal', case=False, na=False)) &
    (pipeline.df['season'] == '2025/2026')
].copy()

# Get one row per match (team-level aggregation)
arsenal_team = arsenal_matches.groupby(['team', 'opponent', 'season', 'gameweek', 'is_home']).agg({
    'xg': 'sum',  # Team's total xG for the match
    'goals': 'sum',  # Team's goals scored
}).reset_index().sort_values('gameweek', ascending=False)

# Get xGA (opponent's xG against Arsenal) by looking up opponent's xG in that match
# We need to find what the opponent generated against Arsenal
opp_stats = pipeline.df.groupby(['team', 'season', 'gameweek']).agg({
    'xg': 'sum', 
    'goals': 'sum'
}).reset_index()
opp_stats = opp_stats.rename(columns={'team': 'opponent', 'xg': 'xga', 'goals': 'goals_conceded'})

arsenal_team = arsenal_team.merge(opp_stats, on=['opponent', 'season', 'gameweek'], how='left')

print("=" * 70)
print("ARSENAL'S LAST 5 GAMES - ACTUAL xG FOR AND AGAINST")
print("=" * 70)
last5 = arsenal_team.head(5)[['gameweek', 'opponent', 'is_home', 'xg', 'goals', 'xga', 'goals_conceded']]
last5.columns = ['GW', 'Opponent', 'Home', 'xG For', 'Goals', 'xGA (opp xG)', 'Conceded']
print(last5.to_string(index=False))
print(f"\n--- Last 5 Game Averages (what roll5 should approximate) ---")
print(f"  Avg xG For:     {last5['xG For'].mean():.3f}")
print(f"  Avg xGA:        {last5['xGA (opp xG)'].mean():.3f}")
print(f"  Avg Goals:      {last5['Goals'].mean():.2f}")
print(f"  Avg Conceded:   {last5['Conceded'].mean():.2f}")

# Now show the rolling features from predictions
print("\n" + "=" * 70)
print("COMPUTED ROLLING FEATURES (grabbed by model for GW25 prediction)")
print("=" * 70)

# Get an Arsenal player from predictions
arsenal_pred = predictions[predictions['team'].str.contains('Arsenal', case=False, na=False)].iloc[0]
print(f"\nArsenal player sampled: {arsenal_pred['player_name']}")

# Show team xG features (offensive)
print(f"\n--- Team xG Rolling (Arsenal's attacking output) ---")
for window in [1, 3, 5, 10, 30]:
    col = f'team_xg_roll{window}'
    if col in arsenal_pred.index:
        print(f"  {col}: {arsenal_pred[col]:.3f}")

# Show team xGA features (defensive - what opponents generate against Arsenal)
print(f"\n--- Team xGA Rolling (what opponents generate vs Arsenal) ---")
for window in [1, 3, 5, 10, 30]:
    col = f'team_xga_roll{window}'
    if col in arsenal_pred.index:
        print(f"  {col}: {arsenal_pred[col]:.3f}")

# Show goals conceded
print(f"\n--- Team Goals Conceded Rolling ---")
for window in [1, 3, 5, 10, 30]:
    col = f'team_conceded_roll{window}'
    if col in arsenal_pred.index:
        print(f"  {col}: {arsenal_pred[col]:.3f}")

======================================================================
ARSENAL'S LAST 5 GAMES - ACTUAL xG FOR AND AGAINST
======================================================================
  GW                Opponent  Home  xG For  Goals  xGA (opp xG)  Conceded
31.0 Wolverhampton Wanderers     0    1.61    2.0          0.30       2.0
27.0       Tottenham Hotspur     0    2.06    4.0          0.76       1.0
26.0               Brentford     0    0.59    1.0          1.50       1.0
25.0              Sunderland     1    1.49    3.0          0.18       0.0
24.0            Leeds United     0    2.20    4.0          0.15       0.0

--- Last 5 Game Averages (what roll5 should approximate) ---
  Avg xG For:     1.590
  Avg xGA:        0.578
  Avg Goals:      2.80
  Avg Conceded:   0.80

======================================================================
COMPUTED ROLLING FEATURES (grabbed by model for GW25 prediction)
======================================================================

Arsenal player sampled: Christian Nørgaard

--- Team xG Rolling (Arsenal's attacking output) ---
  team_xg_roll5: 1.508
  team_xg_roll10: 1.764

--- Team xGA Rolling (what opponents generate vs Arsenal) ---
  team_xga_roll1: 0.760
  team_xga_roll3: 0.813
  team_xga_roll5: 0.658
  team_xga_roll10: 0.953
  team_xga_roll30: 0.819

--- Team Goals Conceded Rolling ---
  team_conceded_roll1: 1.000
  team_conceded_roll3: 0.667
  team_conceded_roll5: 1.000
  team_conceded_roll10: 0.900
  team_conceded_roll30: 0.733

In [8]:
# =============================================================================
# DIAGNOSTIC: Investigate xGA computation bug
# =============================================================================

# Check team name variations in the data
print("Team name variations:")
teams = pipeline.df['team'].unique()
for t in sorted(teams):
    if 'bournemouth' in t.lower() or 'arsenal' in t.lower():
        print(f"  '{t}'")

print("\nOpponent name variations:")
opponents = pipeline.df['opponent'].unique()
for o in sorted(opponents):
    if 'bournemouth' in o.lower() or 'arsenal' in o.lower():
        print(f"  '{o}'")

# Check Arsenal vs Bournemouth game from both perspectives
print("\n" + "=" * 70)
print("Arsenal vs Bournemouth GW20 - BOTH TEAM PERSPECTIVES")
print("=" * 70)

# Arsenal's view (team=Arsenal)
arsenal_view = pipeline.df[
    (pipeline.df['team'].str.contains('Arsenal', case=False)) &
    (pipeline.df['opponent'].str.contains('Bournemouth', case=False)) &
    (pipeline.df['gameweek'] == 20) &
    (pipeline.df['season'] == '2025/2026')
].groupby(['team', 'opponent', 'gameweek']).agg({'xg': 'sum', 'goals': 'sum'}).reset_index()
print("\nArsenal's perspective (team=Arsenal):")
print(arsenal_view)

# Bournemouth's view (team=Bournemouth)  
bournemouth_view = pipeline.df[
    (pipeline.df['team'].str.contains('Bournemouth', case=False)) &
    (pipeline.df['opponent'].str.contains('Arsenal', case=False)) &
    (pipeline.df['gameweek'] == 20) &
    (pipeline.df['season'] == '2025/2026')
].groupby(['team', 'opponent', 'gameweek']).agg({'xg': 'sum', 'goals': 'sum'}).reset_index()
print("\nBournemouth's perspective (team=Bournemouth):")
print(bournemouth_view)

# The xGA for Arsenal SHOULD be Bournemouth's xG (what Bournemouth generated against Arsenal)
if len(bournemouth_view) > 0:
    print(f"\n>>> Arsenal's xGA for GW20 should be: {bournemouth_view['xg'].values[0]:.3f}")
else:
    print("\n>>> ERROR: No Bournemouth perspective found! Team name mismatch?")

Team name variations:
  'Arsenal'
  'Bournemouth'

Opponent name variations:
  'AFC Bournemouth'
  'Arsenal'

======================================================================
Arsenal vs Bournemouth GW20 - BOTH TEAM PERSPECTIVES
======================================================================

Arsenal's perspective (team=Arsenal):
      team         opponent  gameweek    xg  goals
0  Arsenal  AFC Bournemouth      20.0  1.13    3.0

Bournemouth's perspective (team=Bournemouth):
          team opponent  gameweek    xg  goals
0  Bournemouth  Arsenal      20.0  1.43    2.0

>>> Arsenal's xGA for GW20 should be: 1.430

In [9]:
# Quick check: what format do team names actually use?
print("Sample team names:")
print(pipeline.df['team'].value_counts().head(10))
print("\nSample opponent names:")
print(pipeline.df['opponent'].value_counts().head(10))

Sample team names:
team
Brighton and Hove Albion    3198
Liverpool                   3165
Tottenham Hotspur           3158
Wolverhampton Wanderers     3155
Arsenal                     3145
Manchester United           3145
Chelsea                     3142
Newcastle United            3140
Aston Villa                 3138
Crystal Palace              3052
Name: count, dtype: int64

Sample opponent names:
opponent
Manchester City            3177
Wolverhampton Wanderers    3159
Tottenham Hotspur          3140
Brighton & Hove Albion     3137
Aston Villa                3136
Chelsea                    3131
Crystal Palace             3130
West Ham United            3122
Manchester United          3121
Arsenal                    3120
Name: count, dtype: int64